"""add meter_aggregates table

Revision ID: f2673836e8a7
Revises: 8e546274a767
Create Date: 2025-10-22 18:10:41.400634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2673836e8a7'
down_revision: Union[str, Sequence[str], None] = '8e546274a767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meters_id'), table_name='meters')
    op.drop_table('meters')
    op.drop_index(op.f('ix_meter_aggregates_meter_number'), table_name='meter_aggregates')
    op.drop_table('meter_aggregates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_aggregates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('meter_number', sa.VARCHAR(), nullable=False),
    sa.Column('last_entered_units', sa.FLOAT(), nullable=True),
    sa.Column('last_update_at', sa.DATETIME(), nullable=True),
    sa.Column('last_entered_amount', sa.FLOAT(), nullable=True),
    sa.Column('last_payer', sa.VARCHAR(), nullable=True),
    sa.Column('total_dispensed_units', sa.FLOAT(), nullable=False),
    sa.Column('total_token_count', sa.INTEGER(), nullable=False),
    sa.Column('last_token_time', sa.DATETIME(), nullable=True),
    sa.Column('total_amount_paid', sa.FLOAT(), nullable=False),
    sa.Column('total_payment_count', sa.INTEGER(), nullable=False),
    sa.Column('last_payment_time', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_aggregates_meter_number'), 'meter_aggregates', ['meter_number'], unique=1)
    op.create_table('meters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('meter_number', sa.VARCHAR(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meter_number')
    )
    op.create_index(op.f('ix_meters_id'), 'meters', ['id'], unique=False)
    # ### end Alembic commands ###
